# Generated by Django 3.1 on 2020-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_teacher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
