# Generated by Django 3.1 on 2020-08-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200831_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='grade',
        ),
    ]
