# Generated by Django 3.1 on 2020-08-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200831_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.grade'),
            preserve_default=False,
        ),
    ]
