# Generated by Django 3.1 on 2020-08-31 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('course', '0007_auto_20200831_1339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together={('course', 'grade')},
        ),
        migrations.CreateModel(
            name='TutorCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grade')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'course', 'grade')},
            },
        ),
    ]
