# Generated by Django 3.1 on 2020-09-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200831_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='course.grade'),
        ),
    ]
