# Generated by Django 3.1 on 2020-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('info', models.TextField(default='Teacher at Tutor Nepal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
